Affected Issue(s): Fix failing test
What this commit has achieved:
1. Fixed failing tests in `ExampleServerR4IT` due to:
```
org.awaitility.core.ConditionTimeoutException: Condition with ca.uhn.fhir.jpa.starter.ExampleServerR4IT was not fulfilled within 10 seconds.
```
default await time from Awaitility is 10 seconds
2. Added entries in `.gitignore` related to STS IDE